### ISSUE TITLE
iOS 8

### ISSUE THREAD

**Issue by lpfister** [RadiusNetworks/scavenger-hunt-ios-os#2]
Dear all, i tried to compile with iOS 8

Somehow the application does not request for location permission, anyway to fix this?

**Comment by davidgyoung** [comment]
This app has not yet been updated for the iOS 8 permission changes.  You may compile with XCode 5 or make the changes yourself.  See here for details: http://stackoverflow.com/questions/26079530/apple-airlocation-demo-app-ranging-not-shows-beacons/26082348#26082348
