### ISSUE TITLE
There's an awful lot of logging going on

### ISSUE THREAD

**Issue by mharper** [RadiusNetworks/scavenger-hunt-ios-os#5]
In a clean clone of the iOS Scavenger Hunt repo running on an iPhone 6, there is an _awful lot_ of logging that appears in the console.

**Comment by mharper** [comment]
Part of the reason is that the `proximityKit:didEnter:`, `proximityKit:didExit:`, `proximityKit:didDetermineState:forRegion:` and `proximityKit:didRangeBeacons:inRegion:` all contain `NSLog` statements.  And the only method that actually _does_ anything is `proximityKit:didRangeBeacons:inRegion:`!

**Comment by mharper** [comment]
Another contributor (offender?) is `tellHuntAboutRangedBeacons:inRegion:` which has an _enormous_ number of log statements.

**Comment by davidgyoung** [comment]
Well, the last one which does something is the one that gets called every second.  The others get called only when you see or stop seeing a beacon, so they do not generate much noise.

I know you don't like logging.  I do find it very useful in these kinds of callbacks where external events may or may not happen.l depending on all kinds of conditions.  Is bluetooth on?  Is a beacon nearby?  Is the app responding in the background?  Is my beacon battery dead?  Is the identifier wrong?

**Comment by mharper** [comment]
It isn't that I _dislike_ logging per se; it's that I shouldn't have to delete or conditionalize log statements line by line when I want to control logging.  It should be significantly easier to remove the noise from the logs than it currently is.

**Comment by davidgyoung** [comment]
Try this in XCode:

![screen shot 2015-05-09 at 6 03 11 pm](https://cloud.githubusercontent.com/assets/1044849/7552200/bc294ff0-f675-11e4-9347-09d2eadaa237.png)

**Comment by mharper** [comment]
Dude, don't take this so lightly. An `NSLog` killed my brother, ya know.

**Comment by mharper** [comment]
And another thing: _DON'T CALL ME 'HARPER'!_ :imp:

**Comment by csexton** [comment]
Wouldn't have problems if this were written in Swift 😎

**Comment by mattwritescode** [comment]
Dammit you guys I'm really having trouble not jumping in on this conversation. Logs that actually mean things are good. Especially when some random dumbass that you need to help out is having world-ending issues and all you have to do is look at their logs and the problem is solved all the sudden. Ok. That said, I'm cutting off my notifications, and I agree with David here, though Michael is kinda right most of the time. Over and out. I'll hit you guys up in 2016. My tax accountant told me not to work until then.

**Comment by mharper** [comment]
This is one of the best issue threads _evar_.
